RDKC-10381: error:no member named 'mpipeProcessedframes'
Reason for change: Controled mpipe_port.cpp this file content under "_OBJ_DETECTION_" this define
Test Procedure: None
Risks: None

Signed-off-by: seluma611 <Savidha_Elumalai@comcast.com>
(cherry picked from commit 1d93e491696a559a3a2d8a5a65630db61691a541)
Change-Id: I9a5ab2f2b45ab4f4f1bcfd8ba244dc6e07d96601